import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useNavigation } from '@react-navigation/native';

import BackNav from '../components/BackNav';
import { colors, fontSizes, fontWeights, spacing, typography } from '../../design-system/tokens';

const SECTIONS = [
  {
    heading: '',
    body: 'By using SwingSense you agree to these terms. Please read them carefully.',
  },
  {
    heading: 'The Service',
    body: 'SwingSense provides AI-powered baseball swing analysis based on video you upload. Coaching feedback is generated by artificial intelligence and is intended for informational and training purposes only. It is not a substitute for professional in-person coaching.',
  },
  {
    heading: 'Account',
    body: 'You are responsible for maintaining the security of your account. You must provide accurate information during signup. One account per person.',
  },
  {
    heading: 'Content You Upload',
    body: 'You retain ownership of videos you upload. By uploading a video you grant SwingSense a limited license to process it for the purpose of generating your coaching analysis. We do not share your videos with third parties.',
  },
  {
    heading: 'Acceptable Use',
    body: 'You agree not to upload videos containing inappropriate content, use the service for any unlawful purpose, or attempt to reverse-engineer or interfere with the app.',
  },
  {
    heading: 'For Users Under 18',
    body: "If you are under 18, your parent or guardian must agree to these terms on your behalf. Parents are responsible for supervising their child's use of SwingSense.",
  },
  {
    heading: 'Coaching Disclaimer',
    body: 'AI-generated coaching feedback is based on video analysis and should be used as a supplement to — not a replacement for — qualified human coaching. SwingSense makes no guarantee of specific performance improvements.',
  },
  {
    heading: 'Limitation of Liability',
    body: 'SwingSense is provided "as is." We are not liable for any injuries, losses, or damages arising from use of the app or reliance on AI coaching feedback.',
  },
  {
    heading: 'Changes to Terms',
    body: 'We may update these terms at any time. Continued use of the app after changes constitutes acceptance of the new terms.',
  },
  {
    heading: 'Contact',
    body: 'swingsenseapp@gmail.com',
  },
];

export default function TermsOfServiceScreen() {
  const insets = useSafeAreaInsets();
  const navigation = useNavigation();
  return (
    <View style={styles.wrapper}>
      <View style={[styles.backNavWrapper, { paddingTop: insets.top }]}>
        <BackNav label="Profile" onPress={() => navigation.goBack()} />
      </View>
      <ScrollView
        style={styles.scroll}
        contentContainerStyle={[
          styles.content,
          { paddingBottom: insets.bottom + spacing.screen },
        ]}
        showsVerticalScrollIndicator={false}
      >
        <Text style={styles.title}>Terms of Service</Text>
        <Text style={styles.updated}>Last updated: April 18, 2026</Text>
        {SECTIONS.map((section) => (
          <View key={section.heading} style={styles.section}>
            {section.heading ? <Text style={styles.heading}>{section.heading}</Text> : null}
            <Text style={styles.body}>{section.body}</Text>
          </View>
        ))}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  wrapper: { flex: 1, backgroundColor: colors.bg.base },
  backNavWrapper: {
    paddingHorizontal: spacing.screen,
  },
  scroll: { flex: 1 },
  content: { paddingHorizontal: spacing.screen },
  title: {
    fontFamily: typography.displayTitle,
    fontSize: fontSizes.screenTitle,
    color: colors.text.primary,
    marginBottom: spacing.iconGap,
  },
  updated: {
    fontFamily: typography.body,
    fontSize: fontSizes.caption,
    color: colors.text.muted,
    marginBottom: spacing.sectionGap,
  },
  section: { marginBottom: spacing.sectionGap },
  heading: {
    fontFamily: typography.body,
    fontSize: fontSizes.body,
    fontWeight: fontWeights.medium,
    color: colors.text.primary,
    marginBottom: spacing.iconGap,
  },
  body: {
    fontFamily: typography.body,
    fontSize: fontSizes.body,
    color: colors.text.secondary,
    lineHeight: Math.round(fontSizes.body * 1.6),
  },
});
