// Seed script — inserts all 28 drills into Supabase drills table
// Requires service role key to bypass RLS INSERT restriction
//
// Usage:
//   Add SUPABASE_SERVICE_ROLE_KEY to .env, then:
//   node scripts/seed-drills.js

const { createClient } = require('@supabase/supabase-js');

try { require('dotenv').config(); } catch (_) {}

const SUPABASE_URL = 'https://qwzkgyyvtqhdeqkandaf.supabase.co';
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SERVICE_ROLE_KEY) {
  console.error('Error: SUPABASE_SERVICE_ROLE_KEY is not set in your environment.');
  console.error('Add it to .env and run again.');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
  auth: { persistSession: false },
});

const BASE_URL = 'https://qwzkgyyvtqhdeqkandaf.supabase.co/storage/v1/object/public/drill_videos/';
const v = (filename) => BASE_URL + filename;

const drills = [
  {
    name: 'Power position',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['Tee', 'Front toss', 'Overhead', 'Machine'],
    foundation: 'Equipment: bat and tee (or live pitch). Administer as tee work, front toss, overhand, or machine.',
    setup: 'Get in starting stance. Perform your load and stride, then hold. Do not swing yet — freeze at the moment your stride foot lands.',
    focus_points: "Hands stay back. Stride foot is fully down. Weight remains over the back leg. Feel the tension in your lower half — that's the power you're about to release.",
    finish_reminders: 'From the hold position, complete the swing: slot, hip turn, extension through contact. Avoid re-loading or rocking back before you swing.',
    purpose: "Power position trains you to arrive at the right checkpoint before your swing starts. If you can't hold power position with balance, your swing is starting from the wrong place.",
    video_url: v('post-stride.mov'),
    experience_level: 'all',
  },
  {
    name: 'One hand — top hand',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['Tee', 'Front toss'],
    foundation: 'Equipment: bat and tee or front toss. Choke up 6 inches from the knob.',
    setup: 'Get in starting stance. Grip with top hand only, bottom hand off the bat. Load and stride normally.',
    focus_points: 'Maintain palm-up through the entire swing. Keep a level bat path relative to pitch location.',
    finish_reminders: 'Finish the swing completely. Check your hand position at the finish — palm-up should still be intact.',
    purpose: 'Top hand drill trains proper slot and extension. Palm-up through contact creates a direct, powerful path to the ball.',
    video_url: v('top-hand.mov'),
    experience_level: 'all',
  },
  {
    name: 'One hand — bottom hand',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['Tee', 'Front toss'],
    foundation: 'Equipment: bat and tee or front toss. Choke up 6 inches from the knob.',
    setup: 'Get in starting stance. Grip with bottom hand only, top hand off the bat. Load and stride normally.',
    focus_points: 'Maintain palm-down through the entire swing. Keep a level bat path relative to pitch location.',
    finish_reminders: 'Finish the swing completely. Check your hand position at the finish — palm-down should still be intact.',
    purpose: 'Bottom hand drill trains the lead arm through contact. Together with the top hand drill, they build the palm-up/palm-down connection that creates a direct, powerful path to the ball.',
    video_url: v('bottom-hand.mov'),
    experience_level: 'all',
  },
  {
    name: 'Palm up palm down',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['No equipment — shadow drill'],
    foundation: 'No bat or ball needed. This is a shadow drill done at full speed with your hands only.',
    setup: 'Stand in starting stance. Hold your hands in line — bottom hand palm down, top hand palm up. Take a slow-motion swing from your stance.',
    focus_points: 'The moment your stride foot lands, drive your hands forward across your chest. Immediately create the palm-up/palm-down (PUPD) posture as your hands reach the contact zone. Hold PUPD all the way through to your finish.',
    finish_reminders: "Complete the swing maintaining PUPD through the contact point. Don't let the hands roll over early.",
    purpose: 'PUPD is the hand position that produces a direct, powerful bat path. This drill trains your hands to arrive at contact correctly before you ever add a bat or ball.',
    video_url: v('palm-up-palm-down.mov'),
    experience_level: 'all',
  },
  {
    name: 'Chest forward',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['Tee', 'Front toss'],
    foundation: 'Equipment: bat and tee or front toss. Set up with your chest already facing the contact zone.',
    setup: 'Start with your chest facing contact. Load your hands by turning your front shoulder toward contact — this creates your coil. From that coiled position, take your swing.',
    focus_points: 'Keep your hands working in a straight path through contact. Focus on driving the ball up the middle or to the opposite field.',
    finish_reminders: "Finish the swing completely. If you're pulling off or rolling over early, your hand path is breaking down before contact.",
    purpose: 'Chest forward removes hip rotation from the equation and forces your hands and arms to create a direct path to contact. Exposes casting, looping, or hand drift.',
    video_url: v('chest-facing.mov'),
    experience_level: 'all',
  },
  {
    name: 'Drop step',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['No ball — dry drill'],
    foundation: 'No equipment needed. Timing and sequencing drill done without a ball.',
    setup: 'Get in starting stance. Step backward toward the catcher with your back foot. This is the drop step.',
    focus_points: 'Immediately after the drop step, stride forward and swing — all in sequence with no pause. Drop step, stride, swing should flow as one continuous movement.',
    finish_reminders: 'The key is no delay. Back step into forward stride into swing should feel like a single connected motion.',
    purpose: 'The drop step trains the rhythm between your lower half and your swing. Forces you to create momentum forward and time your stride with your hands.',
    video_url: v('drop-step.mov'),
    experience_level: 'all',
  },
  {
    name: 'Toe-heel swing',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['Tee', 'Front toss', 'Overhead', 'Machine'],
    foundation: 'Equipment: bat and tee (or live pitch). Administer as tee work, front toss, overhand, or machine.',
    setup: 'Load and stride, then hold with your stride foot landing on toes only. Do not drop the heel yet.',
    focus_points: 'Stride foot lands on toes only, heel stays up. Drop the heel quickly and let the swing follow immediately.',
    finish_reminders: 'The heel drop and the start of your swing should happen together — not heel drop, pause, then swing.',
    purpose: 'Toe-heel trains the timing connection between foot strike and swing initiation. The heel drop is the trigger that starts your rotation.',
    video_url: v('toe-heel.mov'),
    experience_level: 'all',
  },
  {
    name: 'Waiter',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['No bat — baseball in top hand'],
    foundation: 'No bat. Hold a baseball in your top hand with your palm facing up. The ball rests in your palm — do not grip it.',
    setup: 'Get into power position. Top hand up, palm facing up, ball resting in the palm. Lower half grounded, weight over back leg.',
    finish_reminders: 'Finish with the ball still palm-up in front of you. If the ball falls, your palm rotated.',
    focus_points: 'Drive the ball toward the front of the plate maintaining palm-up the entire way. Do not grip the ball — let it rest.',
    purpose: 'Trains the top hand to stay palm-up from power position through contact — the same position that produces proper slot and extension in the full swing.',
    video_url: v('waiter.mov'),
    experience_level: 'all',
  },
  {
    name: 'Back leg balance swing',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['Tee', 'Front toss', 'Overhead', 'Machine'],
    foundation: 'Equipment: bat and tee (or live pitch). Administer as tee work, front toss, overhand, or machine.',
    setup: 'Get in starting stance. Lift your stride foot and balance entirely on your back leg with a flex in the knee. Hold your coil with stride foot hovering just above the ground.',
    focus_points: 'Maintain balance through the back leg throughout the entire swing. Stride foot hovers — it never plants.',
    finish_reminders: 'Hold your finish on the back leg. If you fall off or shift forward, you broke the drill.',
    purpose: 'Builds balance and teaches you to load and coil without shifting weight forward prematurely. Immediate feedback on where your weight is going.',
    video_url: v('back-leg-balance-swing.mov'),
    experience_level: 'all',
  },
  {
    name: 'Balance back leg hop swing',
    mechanic: null,
    secondary_mechanics: [],
    modalities: [],
    foundation: 'Content pending from Darian.',
    setup: 'Content pending from Darian.',
    focus_points: 'Content pending from Darian.',
    finish_reminders: 'Content pending from Darian.',
    purpose: 'Content pending from Darian.',
    video_url: null,
    experience_level: 'all',
  },
  {
    name: 'Split grip',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['Tee', 'Front toss', 'Overhead', 'Machine'],
    foundation: 'Equipment: bat and tee (or live pitch). Move your top hand 2–4 inches above your bottom hand, splitting the grip before every rep.',
    setup: 'Get in starting stance with the split grip. Load and stride normally.',
    focus_points: 'Take full swings. Focus on the feel through your hands and the bat path through contact.',
    finish_reminders: 'Finish completely. Check whether your hands stayed connected through contact or pulled apart.',
    purpose: 'Heightens feel and proprioception through the hands. Exposes grip tension, rolling over, or loss of connection through contact.',
    video_url: v('split-grip.mov'),
    experience_level: 'all',
  },
  {
    name: 'Walk thru',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['No ball — dry drill or tee'],
    foundation: 'Equipment: bat only, or bat and tee. Start in the back of the box with chest facing contact.',
    setup: 'Back foot steps forward to initiate momentum. Engage stride foot toward contact. Get front shoulder in line with contact. Land the stride.',
    focus_points: 'Use the forward momentum from the walk-through to take a max effort swing. Energy from walking forward should carry directly into your swing.',
    finish_reminders: "Stride landing to swing should be immediate. Don't stop and reset after the walk.",
    purpose: "Trains you to use your whole body's forward momentum in the swing. Teaches what it feels like to have your lower half driving your upper half.",
    video_url: v('walk-thru.mov'),
    experience_level: 'all',
  },
  {
    name: 'Fungo swing',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['Self-toss — bat and baseball'],
    foundation: 'Equipment: bat and one baseball. Top hand on grip, bottom hand holding the ball.',
    setup: 'Get in starting stance. Toss the ball toward the middle-middle contact zone with your bottom hand.',
    focus_points: 'As the ball rises to the contact zone, connect your bottom hand to the grip and take a full swing. Toss and swing timed so hands connect right as the ball arrives.',
    finish_reminders: 'Keep the top hand on the bat the entire time — only the bottom hand tosses and reconnects.',
    purpose: 'Forces you to swing only at a ball in the contact zone. Trains contact point awareness, timing, and bat path without a pitcher or tee.',
    video_url: v('fungo-swing.mov'),
    experience_level: 'all',
  },
  {
    name: 'Tee — middle middle',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['Tee'],
    foundation: 'Equipment: bat and tee. Set tee 2–4 inches in front of plate, height belt-high.',
    setup: 'Set your box placement in relation to the tee. Load and stride into power position.',
    focus_points: "Focus on flush contact — barrel meeting ball squarely. Stay through the ball, don't pull off.",
    finish_reminders: 'Finish with extension through the contact point. Hold the finish and check balance.',
    purpose: 'Foundation of all tee work. Trains your core contact point and establishes base swing path before working to other locations.',
    video_url: v('tee-middle-middle.mov'),
    experience_level: 'all',
  },
  {
    name: 'Tee — middle away',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['Tee'],
    foundation: 'Equipment: bat and tee. Set tee 1–3 inches outside the plate, height belt-high.',
    setup: 'Set box placement so outside pitch is at correct contact point — deeper in the zone. Load and stride into power position.',
    focus_points: "Drive ball to opposite field. Stay inside the ball, don't cast hands out. Let the ball travel deeper before making contact.",
    finish_reminders: "Finish with extension toward opposite field. If you're pulling it, you're hitting it too early.",
    purpose: 'Trains contact point discipline on the outside pitch. Teaches you to stay inside and let the ball come to you.',
    video_url: null,
    experience_level: 'all',
  },
  {
    name: 'Tee — middle in',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['Tee'],
    foundation: 'Equipment: bat and tee. Set tee 2–4 inches in front of plate on inside corner, height belt-high.',
    setup: 'Set box placement so inside pitch is at correct contact point — out front of the plate. Load and stride into power position.',
    focus_points: 'Pull hands through quickly and drive the inside pitch. Get the barrel out front.',
    finish_reminders: 'Finish with hands driving toward the pull side. Extension still happens on inside pitches.',
    purpose: 'Trains you to recognize and attack the inside pitch. Requires quick hands and a contact point further out front than you think.',
    video_url: null,
    experience_level: 'all',
  },
  {
    name: 'Tee — middle high',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['Tee'],
    foundation: 'Equipment: bat and tee. Set tee 2–4 inches in front of plate, height just below chest.',
    setup: "Set box placement. Load and stride into power position. Stay tall — don't drop your back shoulder.",
    focus_points: 'Stay tall and drive through the high pitch. Let your hands work up and through.',
    finish_reminders: 'On a high pitch your finish will be more level to slightly upward — that\'s correct. Avoid dropping the back shoulder.',
    purpose: 'Trains you to stay tall and drive the elevated pitch. Dropping the back shoulder creates a steep upswing path and pop-ups.',
    video_url: v('tee-middle-high.mov'),
    experience_level: 'all',
  },
  {
    name: 'Tee — middle low',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['Tee'],
    foundation: 'Equipment: bat and tee. Set tee 2–4 inches in front of plate, height at knees.',
    setup: 'Set box placement. Load and stride into power position. Low pitch requires a longer bat path — start earlier.',
    focus_points: 'Get the barrel down and through the low pitch. Stay inside the ball.',
    finish_reminders: 'On a low pitch your follow-through will naturally come up — that\'s correct. Avoid scooping or casting under the ball.',
    purpose: 'Trains bat path to the low pitch. Getting the barrel down and through — not under — produces hard contact on low pitches.',
    video_url: v('tee-middle-low.mov'),
    experience_level: 'all',
  },
  {
    name: 'Hip stack',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['No ball — body-weight drill'],
    foundation: 'No equipment needed. Pure body-weight drill focused on lower half movement.',
    setup: 'Get in starting stance. Shift your hips over your back leg — feel your weight fully load over the back leg while maintaining balance.',
    focus_points: 'Weight loads fully over back leg, balance stays intact, upper body stays stacked over your hips.',
    finish_reminders: 'Reset to starting stance and repeat. Slow, controlled movement — feel the difference between starting weight distribution and fully loaded position.',
    purpose: "Isolates the first movement of the load. If you can't feel this clearly, your load isn't happening and your stride will have nothing to push off of.",
    video_url: v('hip-stack.mov'),
    experience_level: 'all',
  },
  {
    name: 'Bat tip stride',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['No ball — shadow drill with bat'],
    foundation: 'Equipment: bat only. No swing, no ball. Slow-motion feel drill.',
    setup: 'Get in starting stance. Begin load — hips over back leg. Simultaneously load hands back while stride foot gains ground toward contact.',
    focus_points: 'Hip load and hand load must happen at the same time, equally. As stride foot moves forward, hands move back — they mirror each other.',
    finish_reminders: 'Hold power position at foot strike and evaluate: hands back, stride foot down, weight over back leg. Reset and repeat.',
    purpose: 'Trains coordination between lower and upper half during the load. If hands load before hips, or hips before hands, timing will be off.',
    video_url: v('bat-tip-stride.mov'),
    experience_level: 'all',
  },
  {
    name: 'Bat tip front',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['Tee', 'Front toss', 'Overhead', 'Machine'],
    foundation: 'Equipment: bat and tee (or live pitch). Administer as tee work, front toss, overhand, or machine.',
    setup: "Get in starting stance. Before you load, position the barrel in front of your head — pointing toward the pitcher. Maintain this barrel position as you load and stride into power position.",
    focus_points: "Keep the barrel in front of your head through the load and stride. Don't let it drift back or drop.",
    finish_reminders: 'From power position, take a full swing. The barrel starts in front and hands load back — exaggerates the separation between hands and barrel.',
    purpose: 'Trains barrel awareness and hand load timing. Starting barrel forward makes you feel what it means to have hands load independently of the barrel — which creates whip and bat speed.',
    video_url: v('bat-tip-front.mov'),
    experience_level: 'all',
  },
  {
    name: 'Gain ground',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['No ball — stride drill'],
    foundation: 'No ball needed. Focus entirely on lower half movement. Can be done with a bat in hand.',
    setup: 'Get in starting stance. Perform your load. Stride — focusing on landing your stride foot 1–4 inches further forward than your starting foot position.',
    focus_points: "Land further than where you started. This is about gaining actual ground toward the pitcher, not just shifting weight.",
    finish_reminders: "After each stride, look down and check: did your foot land further? If it landed in the same spot, you're shifting, not striding.",
    purpose: "Gaining ground means your stride is actually moving toward the pitcher and creating forward momentum. A stride that stays in place loses the momentum advantage.",
    video_url: v('gain-ground.mov'),
    experience_level: 'all',
  },
  {
    name: 'Rope bat',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['Rope bat — dry drill or tee'],
    foundation: 'Equipment: rope bat. Can be used dry or on a tee. No rigid barrel — requires proper sequence to generate whip.',
    setup: 'Get in starting stance with the rope bat. Load and stride into power position.',
    focus_points: 'Drive your hands before the barrel. Hands must lead — if the barrel leads, the rope goes limp.',
    finish_reminders: "Finish with full extension. Rope should whip forward completely — a limp finish means hands didn't drive or you stopped the swing early.",
    purpose: 'Provides immediate feedback on sequencing. Trains slot-to-extension: hands drive first, barrel follows, whip is the result.',
    video_url: v('rope-bat-dry-hack.mov'),
    experience_level: 'all',
  },
  {
    name: 'Framebyframe',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['Tee', 'Front toss', 'Overhead', 'Machine'],
    foundation: 'Equipment: bat and tee (or live pitch). Moves through each checkpoint in sequence at slow speed.',
    setup: 'Get in starting stance. Load and stride to power position — hold. Slow-motion move to slot — hold. Finish swing from slot.',
    focus_points: 'Each hold should be a real stop. Power position: hands back, stride foot down, weight loaded. Slot: back elbow toward rib cage, front elbow working to contact.',
    finish_reminders: 'From slot, finish with full extension. Structure: stance → power position (hold) → slot (hold) → finish.',
    purpose: 'Breaks the swing into three key checkpoints and makes you arrive at each one deliberately. Most efficient way to build checkpoint awareness.',
    video_url: v('power-position-slot-hold-finish-swing.mov'),
    experience_level: 'all',
  },
  {
    name: 'Hold finish A',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['Tee', 'Front toss', 'Overhead', 'Machine'],
    foundation: 'Equipment: bat and tee (or live pitch). Administer as tee work, front toss, overhand, or machine.',
    setup: 'Get in starting stance. Load and stride normally.',
    focus_points: 'Take a full swing and freeze at your finish. Cap of the bat should be facing the pitcher.',
    finish_reminders: "Hold for a full count. Don't let the bat drift or body shift after contact.",
    purpose: 'Confirms you swung through the ball completely with proper extension and follow-through. If cap faces sky or ground, bat path broke down.',
    video_url: v('hold-finish-with-cap-facing-pitcher.mov'),
    experience_level: 'all',
  },
  {
    name: 'Hold finish B',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['Tee', 'Front toss', 'Overhead', 'Machine'],
    foundation: 'Equipment: bat and tee (or live pitch). Administer as tee work, front toss, overhand, or machine.',
    setup: 'Get in starting stance. Load and stride normally.',
    focus_points: 'Take a full swing and hold your follow-through with both hands on the bat. Freeze at the top — weight transferred, back foot up, perfect balance.',
    finish_reminders: "Hold with both hands for a full count. If you're falling off, weight transferred incorrectly.",
    purpose: 'Trains balance and weight transfer. A balanced two-hand finish means lower half drove the swing correctly.',
    video_url: v('hold-finish-after-swing.mov'),
    experience_level: 'all',
  },
  {
    name: 'Dry hack',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['No ball — dry drill'],
    foundation: 'No ball needed. Full swing motion at 50% effort with no ball or tee.',
    setup: 'Get in starting stance. Load and stride normally.',
    focus_points: 'Swing at 50% effort. Feel each phase of the swing without the distraction of making contact. Focus on positions, not outcome.',
    finish_reminders: "Finish should be complete and balanced even at 50%. This is not a half-swing — it's a full swing at reduced effort, no ball.",
    purpose: "Removes the distraction of contact so you can feel what's actually happening in your swing. Best used to rehearse a specific position or feel before adding a ball.",
    video_url: v('dry-hack.mov'),
    experience_level: 'all',
  },
  {
    name: '50% swing',
    mechanic: null,
    secondary_mechanics: [],
    modalities: ['Tee', 'Front toss', 'Overhead', 'Machine'],
    foundation: 'Equipment: bat and tee (or live pitch). Administer at half effort — controlled, reduced-power swing hitting an actual ball.',
    setup: 'Get in starting stance. Load and stride normally.',
    focus_points: "Swing at 50% effort. Goal is to pinpoint the contact zone — feel exactly where the barrel is at contact. Don't try to hit the ball hard.",
    finish_reminders: 'Even at 50%, your finish should be complete and balanced. Full swing, reduced effort.',
    purpose: "Removes the distraction of hitting hard so you can feel what's actually happening. Exposes drift, looping, and contact point issues that full-effort swings mask.",
    video_url: null,
    experience_level: 'all',
  },
];

async function seed() {
  console.log(`Seeding ${drills.length} drills...`);

  const { data, error } = await supabase
    .from('drills')
    .insert(drills)
    .select('id, name');

  if (error) {
    console.error('Insert failed:', error.message);
    process.exit(1);
  }

  console.log(`✓ Inserted ${data.length} drills:`);
  data.forEach(d => console.log(`  ${d.name} (${d.id})`));
}

seed();
