alter table public.drills
  add column if not exists thumbnail_url text;

comment on column public.drills.thumbnail_url is
  'Public URL of a video-frame thumbnail in the drill_thumbnails storage bucket, generated by scripts/generate-drill-thumbnails.js. Null until the script has run for this drill.';
